version: '3'

services:

  glowingbear:
    image: gloweechat-docker:glowingbear
    restart: always
    links:
      - weechat

  weechat:
    image: gloweechat-docker:weechat
    restart: always
    tty: true
    volumes:
      - "/docker/glowing-bear/weechat:/weechat/.weechat"

  bitlbee:
    image: gloweechat-docker:bitlbee
    restart: always
    volumes:
      - "/docker/glowing-bear/bitlbee:/var/lib/bitlbee"

